config/routes.rb
Rails.application.routes.draw do
  
  resources :inutters, only:[:index, :new , :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end
  
  root 'top#index'
  

end

app/models/inutter.rb
class Inutter < ActiveRecord::Base
    #ツイート内容のバリデーションの設定(空白禁止、1〜140文字限定)
    validates :content ,length: { in: 1..140 }  ,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inutters_controller.rb
class InuttersController < ApplicationController
    
    #共通のメソッドへ定義したアクションの事前呼び出し
    before_action :set_tweet, only:[:edit, :update, :destroy] 
    
    #変数の定義のルール！：中身が複数のもの：複数系、単体のもの：単体系
    def index
        @inutters = Inutter.all
    end
    
    #新規作成
    def new
     if params[:back]
      @inutter = Inutter.new(inutters_params)
     else
      @inutter = Inutter.new
     end
    end
    
    def create
        #処理内容①　投稿内容作成
        Inutter.create(inutters_params)
        #処理内容②　リダイレクト
        redirect_to inutters_path
    end

    def confirm
        @inutter = Inutter.new(inutters_params)
        render :new if @inutter.invalid? #確認時のバリデーション
    end
    
    #編集
    def edit

    end

    def update
        if @inutter.update(inutters_params) #値を更新するためにupdateメソッドを使用(引数はblogの内容)
          redirect_to inutters_path,notice:"ブログを更新しました！"#indexアクションにリダイレクト
        else 
          render 'new' #再描画
        end
    end
    
    
    #削除    
    def destroy
        #当該のパラメータを取得
        @inutter = Inutter.find(params[:id])
        #処理内容①　ここでは削除
        @inutter.destroy
        #処理内容②　リダイレクト
        redirect_to inutters_path,notice:"投稿を削除しました！"
    end
    
    #ストロングパラメータ
    private
     def inutters_params
       params.require(:inutter).permit(:content)
     end
     
     #事前に呼び出すアクションの中身
     def set_tweet
        @inutter = Inutter.find(params[:id])
     end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inutters_helper.rb
module InuttersHelper
    
    def choose_new_or_edit
     if action_name == 'new' || action_name == 'confirm'
        confirm_inutters_path
     elsif action_name == 'edit'
        inutter_path
     end
    end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/inutters/_form.html.erb
<!--フォームの宣言-->
<%=form_for(@inutter,url:choose_new_or_edit ) do |f| %>　<!--分岐時にヘルパーメソッドの利用-->
  <% if @inutter.errors.any? %> <!--エラー存在時に以下実行-->
    <div id="error_explanation" >
      <!-- バリデーションエラーの件数を表示-->
      <h2><%= @inutter.errors.count %>件のエラーがあります。</h2>

      <ul>
       <!--@inutter.errorsは@inutterをバリデーションした際のエラー情報-->
       <!--full_messagesは複数のエラーメッセージを表す-->
      <% @inutter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :内容 %>
  <br>
  <%= f.text_field :content,class: 'form-control' %>
  <br>
  <%= f.submit '投稿',class: 'btn btn-primary btn-block' %>
  
<% end %> <!--formの終わりを宣言-->

<%=link_to "投稿一覧へ戻る",inutters_path %>

app/views/inutters/confirm.html.erb
<!--入力確認用フォームの宣言-->
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    
    <h3>以下の内容で投稿する</h3>
    
    <%=form_for(@inutter) do |f| %> 
      <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定。 -->
      <%= f.hidden_field :content %>
    
      <!-- @blog.titleと@blog.contentとすることで、表示用の値を画面に出力 -->
      <p>内容:<%= @inutter.content %></p>
      <%= f.submit "登録する",class: 'btn btn-primary btn-block' %>
    <% end %>
    
    <%= form_for(@inutter, url: new_inutter_path, method: 'get') do |f| %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name:'back',class: 'btn btn-default btn-block'  %>
    <% end %>
    
    <!--前のページへ戻る-->
    <!--<%= link_to '戻る', :back %>-->
  </div>
</div>

app/views/inutters/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>投稿を編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/inutters/index.html.erb
<!--以下はbootstrap使用時の書き方-->
<div class= "container">
  <div class= "wrapper col-md-8 col-md-offset-2 col-sm-10">

  <p><%=notice%></p> <!--フィードバックメッセージの表示-->
  <h1>投稿一覧</h1>
  <%= link_to "投稿する",new_inutter_path,class:'btn btn-default' %>
  <!--<#%= link_to "お問い合わせ",new_contact_path, class:'btn btn-default' %>-->
  
  <% @inutters.each do |inutter| %>
  <div class="row">
    <h4><strong><%= inutter.title %></strong></h4>
      <p><%= inutter.content %></p>
      <%= link_to "編集", edit_inutter_path(inutter.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", inutter_path(inutter.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
  </div>
  <% end %>
  </div>
</div>

app/views/inutters/new.html.erb
<div class="container">
 <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>投稿する！</h2> 
    <p id="notice"><%=notice %></p>
    <%= render 'form' %> <!--共通のフォームを呼び出し-->
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inutter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- スマホやタブレットで崩れないようにするために書く-->
  <%= csrf_meta_tags %>
</head>
<body>
  
<header>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "HOME", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "投稿内容一覧", inutters_path %></li>
            <li><%= link_to "投稿する", new_inutter_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
 </nav>
</header>

<%= yield %>

<footer>
  <p>railsのテストで作ってみた！</p>
  <p>© 2017 Copyright Yoshimitsu Hama .</p>
</footer>

</body>
</html>

app/views/top/index.html.erb
    <p id="notice"> <%= notice %> </p> <!--フラッシュメッセージの表示-->
    
    <section class="about">
        <h2>Inutter</h2>
        <p>
            このアプリはrailsの練習用に作成されました<br>
            犬のデザインが特徴的なTwitter風アプリです！
        </p>
    </section>
    
    <section class="content">
        <div>
        
        </div>
    </section>
    
    <!--<div id="page-top-btn" class="page-top-btn">-->
    <!--    <p><a class="move-page-top" id="move-page-top">▲</a></p>-->
    <!--</div>-->


　　